import { Weapon, WeaponGroupEnum as WType, WeaponDMGTypeEnum as DMG, FireRateEnum, WeaponFactroy as WF, DamageModTypeEnum, ArmorMat, ArmorTypes, Armor} from '../models/equipment.models';
import { DiceRoll as Roll } from '../models/dices.model';
import { RunesEnum as Runes } from '../models/rune.model';
import { LocationsEnum } from '@shared/models/location.model';

export const MELEE_WEAPONS: Weapon[] = [
  WF.createWeapon({ name: 'COMBAT_AXE',         skillName: '1H_AXE',                damage:[new Roll(1, 8, 2)], damageTypes: [DMG.SLASHING],               weight: 2, minSTR: 13, minDEX: 7,  rune: Runes.EARTH }),
  WF.createWeapon({ name: 'WAR_AXE',            skillName: '1H_AXE', ap: 4, mr: 4,  damage:[new Roll(1, 4, 2)], damageTypes: [DMG.SLASHING],                          minSTR: 6,  minDEX: 6,  rune: Runes.EARTH }),
  WF.createWeapon({ name: 'SMALL_PICKAXE',      skillName: '1H_AXE',                damage:[new Roll(1, 6, 2)], damageTypes: [DMG.SLASHING, DMG.IMPALING],            minSTR: 7,  minDEX: 7,  rune: Runes.EARTH }),
  WF.createWeapon({ name: 'SMALL_AXE',          skillName: '1H_AXE', ap: 6, mr: 4,  damage:[new Roll(1, 6, 2)], damageTypes: [DMG.SLASHING],                          minSTR: 7,  minDEX: 7,  rune: Runes.EARTH }),
  WF.createWeapon({ name: 'BATTLE_AXE',         skillName: '2H_AXE',                damage:[new Roll(1, 8, 2)], damageTypes: [DMG.SLASHING],               weight: 2, minSTR: 9,  minDEX: 7,   rune: Runes.EARTH, twoHanded: true}),
  WF.createWeapon({ name: 'DAGGER_AXE',         skillName: '2H_AXE', ap: 10,        damage:[new Roll(3, 6)],    damageTypes: [DMG.SLASHING],               weight: 3, minSTR: 13, minDEX: 9,  rune: Runes.EARTH, twoHanded: true}),
  WF.createWeapon({ name: 'GREAT_AXE',          skillName: '2H_AXE', ap: 10, mr: 1, damage:[new Roll(2, 6, 2)], damageTypes: [DMG.SLASHING],               weight: 2, minSTR: 11, minDEX: 7,  rune: Runes.EARTH, twoHanded: true}),
  WF.createWeapon({ name: 'PICK_AXE',           skillName: '2H_AXE',         mr: 2, damage:[new Roll(2, 8, 2)], damageTypes: [DMG.SLASHING],               weight: 2, minSTR: 9,  minDEX: 9,   rune: Runes.EARTH, twoHanded: true}),
  WF.createWeapon({ name: 'HALF_MOON_AXE',      skillName: '2H_AXE',         mr: 2, damage:[new Roll(2, 6, 2)], damageTypes: [DMG.SLASHING],               weight: 2, minSTR: 10, minDEX: 10, rune: Runes.MOON,  twoHanded: true}),
  WF.createWeapon({ name: 'WIDE_ORLANTH_AXE',   skillName: '2H_AXE', ap: 10, mr: 0, damage:[new Roll(2, 8, 2)], damageTypes: [DMG.SLASHING],               weight: 3, minSTR: 12, minDEX: 10, rune: Runes.EARTH, twoHanded: true}),
  WF.createWeapon({ name: 'PICKAXE',            skillName: '2H_AXE',         mr: 1, damage:[new Roll(2, 8)],    damageTypes: [DMG.SLASHING, DMG.IMPALING], weight: 2, minSTR: 11, minDEX: 7,  rune: Runes.EARTH, twoHanded: true}),
  WF.createWeapon({ name: 'LUMBERJACK_AXE',     skillName: '2H_AXE',         mr: 1,   damage:[new Roll(2, 6)],     damageTypes: [DMG.SLASHING], weight: 2, minSTR: 10, minDEX: 12, rune: Runes.EARTH, twoHanded: true}),
  WF.createWeapon({ name: 'WOODEN_CLUB',        skillName: '1H_HAMMER', mr: 4, ap: 4, damage:[new Roll(1, 6)],     damageTypes: [DMG.CRUSHING], weight: 0.5, minDEX: 7, minSTR: 7 }),
  WF.createWeapon({ name: 'HAMMER',             skillName: '1H_HAMMER', mr: 3, ap: 8, damage:[new Roll(1, 4, 2)],  damageTypes: [DMG.CRUSHING], weight: 1, minDEX: 7, minSTR: 9 }),
  WF.createWeapon({ name: 'WARHAMMER',          skillName: '1H_HAMMER', mr: 3, ap: 10, damage:[new Roll(1, 6, 2)], damageTypes: [DMG.CRUSHING], weight: 1, minDEX: 9, minSTR: 11 }),
  WF.createWeapon({ name: 'GREAT_CLUB',         skillName: '2H_HAMMER', mr: 1, ap: 12,  damage:[new Roll(2, 6)],    damageTypes: [DMG.CRUSHING], weight: 3, minDEX: 9, minSTR: 13, twoHanded: true }),
  WF.createWeapon({ name: 'GREAT_HAMMER',       skillName: '2H_HAMMER', mr: 1, ap: 5,  damage:[new Roll(2, 6, 2)],  damageTypes: [DMG.CRUSHING], weight: 3, minDEX: 9, minSTR: 9, twoHanded: true }),
  WF.createWeapon({ name: 'MAUL',               skillName: '2H_HAMMER', mr: 1, ap: 12,  damage:[new Roll(2, 8)],    damageTypes: [DMG.CRUSHING], weight: 3, minDEX: 7, minSTR: 11, twoHanded: true }),
  WF.createWeapon({ name: 'HEAVY_MACE',         skillName: '1H_MACE', ap: 10, mr: 3, damage:[new Roll(1, 8, 2)], damageTypes: [DMG.CRUSHING], weight: 2,   minSTR: 13, minDEX: 7, rune: Runes.DARKNESS }),
  WF.createWeapon({ name: 'LIGHT_MACE',         skillName: '1H_MACE', ap: 6, mr: 3, damage:[new Roll(1, 6, 2)],  damageTypes: [DMG.CRUSHING], weight: 1,   minSTR:  7, minDEX: 7, rune: Runes.DARKNESS }),
  WF.createWeapon({ name: 'SINGLESTICK',        skillName: '1H_MACE', ap: 5, mr: 4, damage:[new Roll(1, 6)],     damageTypes: [DMG.CRUSHING], weight: 0.5, minSTR:  0, minDEX: 9, rune: Runes.DARKNESS }),
  WF.createWeapon({ name: 'POLE_HAMMER',        skillName: '2H_MACE', ap: 12, mr: 0, damage:[new Roll(1, 8, 1)], damageTypes: [DMG.CRUSHING],  weight: 3, minSTR: 11, minDEX: 7, rune: Runes.DARKNESS, twoHanded: true}),
  WF.createWeapon({ name: '2H_MAUL',            skillName: '2H_MACE', ap: 10, mr: 3, damage:[new Roll(1, 8, 2)], damageTypes: [DMG.CRUSHING],  weight: 2, minSTR: 9, minDEX: 7,  rune: Runes.DARKNESS, twoHanded: true}),
  WF.createWeapon({ name: 'QARTERSTARFF',       skillName: '2H_MACE', ap:  8, mr: 0, damage:[new Roll(1, 8)],    damageTypes: [DMG.CRUSHING],  weight: 2, minSTR: 9, minDEX: 9,  rune: Runes.DARKNESS, twoHanded: true}),
  WF.createWeapon({ name: '2H_LASSO',           skillName: 'LASSO', mr: 0, ap: 4, damage:[], damageTypes: [DMG.SLASHING],  weight: 1, minDEX: 9, minSTR: 9 }),
  WF.createWeapon({ name: 'NET',                skillName: 'NET', mr: 2, ap: 15, damage:[], damageTypes: [], weight: 2, minDEX: 9, minSTR: 11, rune: Runes.WATER }),
  WF.createWeapon({ name: 'GREAT_NET',          skillName: 'NET',          mr: 1, ap: 15, damage:[], damageTypes: [], weight: 3, minDEX: 9, minSTR: 11, rune: Runes.WATER }),
  WF.createWeapon({ name: 'ROPE_DART',          skillName: 'ROPE_DART',     mr: 0, ap: 4, damage:[new Roll(1, 3)],    damageTypes: [DMG.IMPALING],  weight: 1, minDEX: 11, minSTR: 9 }),
  WF.createWeapon({ name: 'THROWING_HOOK',      skillName: 'THROWING_HOOK', mr: 0, ap: 4, damage:[new Roll(1, 4, 1)], damageTypes: [DMG.SLASHING],  weight: 1, minDEX: 11, minSTR: 7 }),
  WF.createWeapon({ name: 'WHIP',               skillName: '1H_WHIP',       mr: 1, ap: 4, damage:[new Roll(1, 3)],    damageTypes: [DMG.SLASHING],  weight: 0.5, minDEX: 7, minSTR: 7 }),
  WF.createWeapon({ name: 'LASH',               skillName: '1H_WHIP',       mr: 0, ap: 6, damage:[new Roll(0, 0, 1)], damageTypes: [DMG.SLASHING],  weight: 0.5, minDEX: 7, minSTR: 7 }),
  WF.createWeapon({ name: 'GREAT_CHAIN',        skillName: '2H_WHIP',       mr: 0, ap: 12, damage:[new Roll(1, 4)],   damageTypes: [DMG.SLASHING],  weight: 2, minDEX: 7, minSTR: 11 }),
  WF.createWeapon({ name: 'SPIKE_CHAIN',        skillName: '2H_WHIP',       mr: 0, ap: 12, damage:[new Roll(1, 4, 2)], damageTypes: [DMG.IMPALING], weight: 3, minDEX: 9, minSTR: 11 }),
  WF.createWeapon({ name: 'POLE_LASSO',         skillName: 'LASSO', mr: 0, ap: 4, damage:[], damageTypes: [],       weight: 3, minDEX: 13, minSTR: 9 }),
  WF.createWeapon({ name: 'FALX',               skillName: 'POLE_AXE', mr: 0, ap: 10, damage:[new Roll(2, 6, 2)], damageTypes: [DMG.CUT_AND_THRUSH],       weight: 3, minDEX: 7, minSTR: 11 }),
  WF.createWeapon({ name: 'HALBERD',            skillName: 'POLE_AXE', mr: 0, ap: 10, damage:[new Roll(3, 6)],    damageTypes: [DMG.CUT_AND_THRUSH],       weight: 3, minDEX: 7, minSTR: 11 }),
  WF.createWeapon({ name: 'MOON_BLADE',         skillName: 'POLE_AXE', mr: 0, ap: 12, damage:[new Roll(2, 6, 1)], damageTypes: [DMG.CUT_AND_THRUSH], weight: 2, minDEX: 11, minSTR: 9, rune: Runes.MOON, twoHanded: true }),
  WF.createWeapon({ name: 'POLE_AXE',           skillName: 'POLE_AXE', mr: 0, ap: 10, damage:[new Roll(2, 6, 2)],  damageTypes: [DMG.SLASHING],       weight: 3, minDEX: 7, minSTR: 9, twoHanded: true }),
  WF.createWeapon({ name: 'POLE_HOOK',          skillName: 'POLE_AXE', mr: 0, ap: 8,  damage:[new Roll(2, 4, 2)],  damageTypes: [DMG.CUT_AND_THRUSH], weight: 3, minDEX: 7, minSTR: 9, twoHanded: true }),
  WF.createWeapon({ name: 'JAVELIN',            skillName: '1H_SPEAR', mr: 2,                                     damageTypes: [DMG.IMPALING],            minDEX: 9, minSTR: 9, rune: Runes.FIRE }),
  WF.createWeapon({ name: 'SHORTSPEAR',         skillName: '1H_SPEAR', mr: 2, ap: 10, damage:[new Roll(1, 6, 1)], damageTypes: [DMG.IMPALING], weight: 2, minDEX: 9, minSTR: 7, rune: Runes.FIRE }),
  WF.createWeapon({ name: 'LANCE',              skillName: '1H_SPEAR', mr: 0, ap: 10, damage:[new Roll(1, 10, 1)],damageTypes: [DMG.IMPALING], weight: 3, minDEX: 9, minSTR: 7, rune: Runes.FIRE }),
  WF.createWeapon({ name: 'TRIDENT',            skillName: '1H_SPEAR', mr: 1,         damage:[new Roll(2, 3)],    damageTypes: [DMG.IMPALING], weight: 2, minDEX: 0, minSTR: 7, rune: Runes.WATER }),
  WF.createWeapon({ name: 'FORK',               skillName: '1H_SPEAR', mr: 0,         damage:[new Roll(1, 6, 1)],    damageTypes: [DMG.IMPALING], weight: 3, minDEX: 9, minSTR: 9, rune: Runes.FIRE, twoHanded: true }),
  WF.createWeapon({ name: 'PIKE',               skillName: '1H_SPEAR', mr: 0, ap: 12, damage:[new Roll(2, 6, 1)],    damageTypes: [DMG.IMPALING], weight: 3, minDEX: 7, minSTR: 11, rune: Runes.FIRE, twoHanded: true }),
  WF.createWeapon({ name: 'POLE_SWORD',         skillName: '2H_SPEAR', mr: 0, ap: 10, damage:[new Roll(1, 8, 2)],    damageTypes: [DMG.CUT_AND_THRUSH], weight: 3, minDEX: 7, minSTR: 11, twoHanded: true }),
  WF.createWeapon({ name: 'LONGSPEAR',          skillName: '2H_SPEAR', mr: 0, ap: 10, damage:[new Roll(1, 10, 1)],    damageTypes: [DMG.IMPALING], weight: 3, minDEX: 7, minSTR: 9, rune: Runes.FIRE, twoHanded: true }),
  WF.createWeapon({ name: 'SHORTSPEAR_2M',      skillName: '2H_SPEAR', mr: 1, ap: 10, damage:[new Roll(1, 8, 1)],     damageTypes: [DMG.IMPALING], weight: 3, minDEX: 7, minSTR: 7, rune: Runes.FIRE, twoHanded: true }),
  WF.createWeapon({ name: 'SWORD_STAFF',        skillName: '2H_SPEAR', mr: 1, ap: 12, damage:[new Roll(2, 4, 1)],     damageTypes: [DMG.CUT_AND_THRUSH], weight: 2, minDEX: 9, minSTR: 9, twoHanded: true }),
  WF.createWeapon({ name: 'TRIDENT_2M',         skillName: '2H_SPEAR', mr: 1, damage:[new Roll(2, 3, 1)],             damageTypes: [DMG.IMPALING], weight: 2, minDEX: 0, minSTR: 7, rune: Runes.WATER, twoHanded: true }),
  WF.createWeapon({ name: 'DAGGER',             skillName: 'DAGGER', mr: 4, damage:[new Roll(1, 4, 2)], damageTypes: [DMG.CUT_AND_THRUSH], weight: 0.25, minDEX: 0, minSTR: 0 }),
  WF.createWeapon({ name: 'PARRYNG_DAGGER',     skillName: 'DAGGER', mr: 4, damage:[new Roll(1, 4, 2)], damageTypes: [DMG.CUT_AND_THRUSH], weight: 0.35, minDEX: 0, minSTR: 0 }),
  WF.createWeapon({name:'THROWING_DAGGER_MELEE', skillName:'DAGGER', mr: 4, damage:[new Roll(1, 4)],    damageTypes: [DMG.CUT_AND_THRUSH], weight: 0.15, minDEX: 9, minSTR: 0 }),
  WF.createWeapon({ name: 'ESROLIAN_KNIFE',     skillName: 'DAGGER', mr: 4, damage:[new Roll(1, 3, 1)], damageTypes: [DMG.SLASHING],       weight: 0.25, minDEX: 6, minSTR: 6 }),
  WF.createWeapon({ name: 'FLENSING_KNIFE',     skillName: 'DAGGER', mr: 4, damage:[new Roll(1, 6)],    damageTypes: [DMG.SLASHING],       weight: 0.35, minDEX: 0, minSTR: 8 }),
  WF.createWeapon({ name: 'STONE_KNIFE',        skillName: 'DAGGER', mr: 4, damage:[new Roll(1, 3, 1)], damageTypes: [DMG.SLASHING],       weight: 0.15, minDEX: 0, minSTR: 0 }),
  WF.createWeapon({ name: 'SICKLE',             skillName: 'DAGGER', mr: 3, damage:[new Roll(1, 6, 1)], damageTypes: [DMG.CUT_AND_THRUSH], weight: 0.1 , minDEX: 0, minSTR: 0 }),
  WF.createWeapon({ name: 'BROADSWORD',         skillName: '1H_SWORD', mr: 2, ap: 12, damage:[new Roll(1, 8, 1)],  damageTypes: [DMG.CUT_AND_THRUSH], weight: 1, minDEX: 9, minSTR: 7, rune: Runes.AIR }),
  WF.createWeapon({ name: 'KOPIS',              skillName: '1H_SWORD', mr: 2, ap: 12, damage:[new Roll(1, 8, 1)],  damageTypes: [DMG.SLASHING],       weight: 1, minDEX: 9, minSTR: 9, rune: Runes.MOON }),
  WF.createWeapon({ name: 'RAPIER',             skillName: '1H_SWORD', mr: 2, ap: 8 , damage:[new Roll(1, 6, 1)],  damageTypes: [DMG.CUT_AND_THRUSH], weight: 1, minDEX: 7, minSTR: 13, rune: Runes.AIR }),
  WF.createWeapon({ name: 'SHORT_SWORD',        skillName: '1H_SWORD', mr: 3, ap: 12, damage:[new Roll(1, 6, 1)],  damageTypes: [DMG.CUT_AND_THRUSH], weight: 1, minDEX: 0, minSTR: 0, rune: Runes.AIR }),
  WF.createWeapon({ name: 'GREATSWORD',         skillName: '2H_SWORD', mr: 1, ap: 12, damage:[new Roll(2, 8)],     damageTypes: [DMG.SLASHING], weight: 2, minDEX: 11, minSTR: 13, rune: Runes.AIR, twoHanded: true }),
  WF.createWeapon({ name: 'PHOMPHAIA',          skillName: '2H_SWORD', mr: 2, ap: 10, damage:[new Roll(2, 6, 2)],  damageTypes: [DMG.SLASHING], weight: 2, minDEX: 11, minSTR:  9, rune: Runes.MOON, twoHanded: true }),
  WF.createWeapon({ name: 'SICKLE_SWORD',       skillName: '2H_SWORD', mr: 2, ap: 12, damage:[new Roll(1, 10, 1)], damageTypes: [DMG.SLASHING], weight: 1, minDEX:  9, minSTR:  9, rune: Runes.MOON, twoHanded: true }),
  WF.createWeapon({ name: 'ARMORED_GLOVE',      skillName: 'FIST', mr: 3, ap: 8, damage:[new Roll(1, 3)],     damageTypes: [DMG.HAND_TO_HAND], weight: 1, minDEX:  0, minSTR:  10 }),
  WF.createWeapon({ name: 'HEAVY_CESTUS',       skillName: 'FIST', mr: 4, ap: 8, damage:[new Roll(1, 3, 2)],  damageTypes: [DMG.HAND_TO_HAND], weight: 1, minDEX:  0, minSTR:  11 }),
  WF.createWeapon({ name: 'LIGHT_CESTUS',       skillName: 'FIST', mr: 4, ap: 4, damage:[new Roll(1, 3, 1)],  damageTypes: [DMG.HAND_TO_HAND], weight: 0.5, minDEX:  0, minSTR:  7 }),
  WF.createWeapon({ name: 'CLAW',               skillName: 'FIST', mr: 4, ap: 0, damage:[new Roll(1, 4, 1)],  damageTypes: [DMG.CUT_AND_THRUSH], weight: 1, minDEX:  9, minSTR:  7 }),
  WF.createWeapon({ name: 'FIST',               skillName: 'FIST', mr: 4, ap: 0, damage:[new Roll(1, 3)],     damageTypes: [DMG.HAND_TO_HAND], weight: 0, minDEX:  0, minSTR:  0 }),
  WF.createWeapon({ name: 'KNUCKLE_STRIP',      skillName: 'FIST', mr: 4, ap: 5, damage:[new Roll(1, 3, 1)],  damageTypes: [DMG.HAND_TO_HAND], weight: 0.35, minDEX:  0, minSTR:  10 }),
  WF.createWeapon({ name: 'WRIST_WRAPPINGS',    skillName: 'FIST', mr: 4, ap: 2, damage:[new Roll(1, 3, 1)],  damageTypes: [DMG.HAND_TO_HAND], weight: 1, minDEX:  0, minSTR:  0 }),
  WF.createWeapon({ name: 'GRAPPLE',            skillName: 'GRAPPLE',  mr: 4, ap: 0, damage:[],                 damageTypes: [DMG.HAND_TO_HAND], weight: 0, minDEX:  0, minSTR:  0 }),
  WF.createWeapon({ name: 'LIGHT_ITEM',         skillName: 'IMPROVISED', mr: 4, ap: 0, damage:[new Roll(1, 3)], damageTypes: [DMG.CRUSHING], weight: 0, minDEX: 0, minSTR: 0 }),
  WF.createWeapon({ name: 'MEDIUM_ITEM',        skillName: 'IMPROVISED', mr: 3, ap: 0, damage:[new Roll(1, 6)], damageTypes: [DMG.CRUSHING], weight: 0, minDEX: 9, minSTR: 7 }),
  WF.createWeapon({ name: 'HEAVY_ITEM',         skillName: 'IMPROVISED', mr: 4, ap: 0, damage:[new Roll(1, 8)], damageTypes: [DMG.CRUSHING], weight: 0, minDEX: 11, minSTR: 9 }),
  WF.createWeapon({ name: 'GIANT_ITEM',         skillName: 'IMPROVISED', mr: 4, ap: 0, damage:[new Roll(1, 10)],damageTypes: [DMG.CRUSHING], weight: 0, minDEX: 13, minSTR: 9 }),
  WF.createWeapon({ name: 'POINTED_ITEM',       skillName: 'IMPROVISED', mr: 3, ap: 0, damage:[new Roll(1, 6, 1)], damageTypes: [DMG.IMPALING], weight: 0, minDEX: 9, minSTR: 9 }),
  WF.createWeapon({ name: 'EDGED_ITEM',         skillName: 'IMPROVISED', mr: 3, ap: 0, damage:[new Roll(1, 6)], damageTypes: [DMG.SLASHING], weight: 0, minDEX: 9, minSTR: 7 }),
  WF.createWeapon({ name: 'BOOT_BLADE',         skillName: 'KICK', mr: 2, ap: 6, damage:[new Roll(1, 6, 1)], damageTypes: [DMG.HAND_TO_HAND], weight: 1, minDEX: 0, minSTR: 10 }),
  WF.createWeapon({ name: 'KICK',               skillName: 'KICK', mr: 4, ap: 0, damage:[new Roll(1, 6)],    damageTypes: [DMG.HAND_TO_HAND], weight: 0, minDEX: 0, minSTR: 0 }),
  WF.createWeapon({ name: 'BITE',               skillName: 'BITE', mr: 4, ap: 0, damage:[new Roll(1, 6)],    damageTypes: [DMG.HAND_TO_HAND], weight: 0, minDEX: 0, minSTR: 0 }),
];

export const RANGED_WEAPONS: Weapon[] = [
  WF.createWeapon({ name: 'LONGBOW',             skillName: 'BOW',      skillGroup: WType.RANGED, damage: [new Roll(1, 8, 1)], ap: 6, damageTypes: [DMG.IMPALING], weight: 3, minSTR: 11, minDEX: 9, twoHanded: true, rune: Runes.FIRE, fireRate: FireRateEnum.S_MR, rangue: 250, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'COMPOSITE_BOW',       skillName: 'BOW',      skillGroup: WType.RANGED, damage: [new Roll(1, 8, 1)], ap: 7, damageTypes: [DMG.IMPALING], weight: 2, minSTR: 13, minDEX: 9, twoHanded: true, rune: Runes.FIRE, fireRate: FireRateEnum.S_MR, rangue: 100, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'ELF_BOW',             skillName: 'BOW',      skillGroup: WType.RANGED, damage: [new Roll(1, 8, 1)], ap: 6, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  9, minDEX: 9, twoHanded: true, rune: Runes.FIRE, fireRate: FireRateEnum.S_MR, rangue:  80, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'SELF_BOW',            skillName: 'BOW',      skillGroup: WType.RANGED, damage: [new Roll(1, 6, 1)], ap: 5, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  9, minDEX: 9, twoHanded: true, rune: Runes.FIRE, fireRate: FireRateEnum.S_MR, rangue:  80, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'HORSE_BOW',           skillName: 'BOW',      skillGroup: WType.RANGED, damage: [new Roll(1, 6)],    ap: 4, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  7, minDEX: 9, twoHanded: true, rune: Runes.FIRE, fireRate: FireRateEnum.S_MR, rangue:  60, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'ARBALEST',            skillName: 'CROSSBOW', skillGroup: WType.RANGED, damage: [new Roll(3, 6, 1)], ap: 10, damageTypes: [DMG.IMPALING], weight: 3, minSTR: 13, minDEX: 7, twoHanded: true, fireRate: FireRateEnum.E_5R, rangue: 150, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'HEAVY_CROSSBOW',      skillName: 'CROSSBOW', skillGroup: WType.RANGED, damage: [new Roll(2, 6, 2)], ap: 10, damageTypes: [DMG.IMPALING], weight: 2, minSTR: 11, minDEX: 7, twoHanded: true, fireRate: FireRateEnum.E_3R, rangue: 120, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'MEDIUM_CROSSBOW',     skillName: 'CROSSBOW', skillGroup: WType.RANGED, damage: [new Roll(2, 6, 1)], ap:  8, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  9, minDEX: 7, twoHanded: true, fireRate: FireRateEnum.E_2R, rangue: 110, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'LIGHT_CROSSBOW',      skillName: 'CROSSBOW', skillGroup: WType.RANGED, damage: [new Roll(2, 4, 2)], ap:  6, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  7, minDEX: 7, twoHanded: true, fireRate: FireRateEnum.E_2R, rangue: 100, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'REPEATING_CROSSBOW',  skillName: 'CROSSBOW', skillGroup: WType.RANGED, damage: [new Roll(2, 4, 2)], ap:  6, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  7, minDEX: 7, twoHanded: true, fireRate: FireRateEnum.E_MR, rangue: 100, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'STONE_BOW',           skillName: 'CROSSBOW', skillGroup: WType.RANGED, damage: [new Roll(1, 8, 2)], ap:  6, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  7, minDEX: 7, twoHanded: true, fireRate: FireRateEnum.E_2R, rangue:  80, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'PISTOL_CROSSBOW',     skillName: 'CROSSBOW', skillGroup: WType.RANGED, damage: [new Roll(2, 4)],    ap:  5, damageTypes: [DMG.IMPALING], weight: 2, minSTR:  7, minDEX: 9, twoHanded: false,fireRate: FireRateEnum.E_MR, rangue:  40, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'AMENTUM',             skillName: 'ATLATL',   skillGroup: WType.RANGED, damage: [new Roll(1, 4)],    ap: 3, damageTypes: [DMG.IMPALING], weight: 0.25, minSTR: 9, minDEX: 9, twoHanded: true, fireRate: FireRateEnum.E_MR, rangue:  5, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'ATLATL',              skillName: 'ATLATL',   skillGroup: WType.RANGED, damage: [new Roll(1, 6)],    ap: 6, damageTypes: [DMG.IMPALING], weight: 0.5,  minSTR: 9, minDEX: 9, twoHanded: true, fireRate: FireRateEnum.E_MR, rangue: 10, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'ATLATL',              skillName: 'ATLATL',   skillGroup: WType.RANGED, damage: [new Roll(1, 4)],    ap: 3, damageTypes: [DMG.IMPALING], weight: 0.25, minSTR: 0, minDEX: 9, twoHanded: true, fireRate: FireRateEnum.E_MR, rangue: 10, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name: 'BLOWGUN',             skillName: 'BLOWGUN',  skillGroup: WType.RANGED, damage: [new Roll(1, 2)],    ap: 4, damageTypes: [DMG.IMPALING], weight: 1, minSTR: 0, minDEX: 9, twoHanded: true, fireRate: FireRateEnum.E_MR, rangue: 20, damageModType: DamageModTypeEnum.NONE }),
  WF.createWeapon({ name:'DART',                 skillName: 'JABELIN',  skillGroup: WType.RANGED, damage: [new Roll(1, 6)],    ap: 4, damageTypes: [DMG.IMPALING], weight: 0.5, minSTR: 0, minDEX: 9,                   fireRate: FireRateEnum.S_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'FEATHERED_DART',       skillName: 'JABELIN',  skillGroup: WType.RANGED, damage: [new Roll(1, 4, 1)], ap: 8, damageTypes: [DMG.IMPALING], weight: 1,   minSTR: 9, minDEX: 9,                   fireRate: FireRateEnum.E_MR, rangue: 30, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'JAVELIN_THROWING',     skillName: 'JABELIN',  skillGroup: WType.RANGED, damage: [new Roll(1, 10)],   ap: 8, damageTypes: [DMG.IMPALING], weight: 1,   minSTR: 9, minDEX: 9, rune: Runes.FIRE, fireRate: FireRateEnum.E_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'SHORT_SPEAR_THROWING', skillName: 'JABELIN',  skillGroup: WType.RANGED, damage: [new Roll(1, 6, 1)], ap: 10,damageTypes: [DMG.IMPALING], weight: 2,   minSTR: 9, minDEX: 7, rune: Runes.FIRE, fireRate: FireRateEnum.E_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'KESTROS',              skillName: 'SLING',   skillGroup: WType.RANGED, damage: [new Roll(1, 8, 1)], ap: 0, damageTypes: [DMG.IMPALING], weight: 1,   minSTR: 9, minDEX: 11,                  fireRate: FireRateEnum.E_MR, rangue: 50, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'SLING',                skillName: 'SLING',   skillGroup: WType.RANGED, damage: [new Roll(1, 8)],    ap: 0, damageTypes: [DMG.CRUSHING], weight: 1,   minSTR: 0, minDEX:  9,                  fireRate: FireRateEnum.S_MR, rangue: 80, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'STAFF_SLING',          skillName: 'SLING',   skillGroup: WType.RANGED, damage: [new Roll(1, 10)],   ap: 0, damageTypes: [DMG.CRUSHING], weight: 2,   minSTR: 9, minDEX:  9,                  fireRate: FireRateEnum.E_MR, rangue: 100, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'AXE_THROWING',         skillName: 'AXE_THROWING',   skillGroup: WType.RANGED, damage: [new Roll(1, 6)],    ap: 6, damageTypes: [DMG.IMPALING], weight: 1,    minSTR: 9, minDEX: 9, rune: Runes.EARTH, fireRate: FireRateEnum.S_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'HUNTING_BOOMERANG',    skillName: 'BOOMERANG',      skillGroup: WType.RANGED, damage: [new Roll(1, 6)],    ap: 5, damageTypes: [DMG.CRUSHING], weight: 0.33, minSTR: 7, minDEX: 11,                   fireRate: FireRateEnum.E_MR, rangue: 40, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'WAR_BOOMERANG',        skillName: 'BOOMERANG',      skillGroup: WType.RANGED, damage: [new Roll(1, 8)],    ap: 8, damageTypes: [DMG.CRUSHING], weight: 1,    minSTR: 9, minDEX: 11,                   fireRate: FireRateEnum.E_MR, rangue: 30, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'SMALL_DART',           skillName: 'DART',           skillGroup: WType.RANGED, damage: [new Roll(1, 4)],    ap: 2, damageTypes: [DMG.IMPALING], weight: 0.33, minSTR: 0, minDEX: 9,                    fireRate: FireRateEnum.S_MR, rangue: 10, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'THROWING_CLUB',        skillName: 'THROWING_CLUB',  skillGroup: WType.RANGED, damage: [new Roll(1, 6)],    ap: 5, damageTypes: [DMG.CRUSHING], weight: 1,    minSTR: 7, minDEX: 9,                    fireRate: FireRateEnum.S_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'THROWING_DAGGER',      skillName: 'THROWING_DAGGER',skillGroup: WType.RANGED, damage: [new Roll(1, 4)],    ap: 6, damageTypes: [DMG.IMPALING], weight: 0.25, minSTR: 0, minDEX: 9,                    fireRate: FireRateEnum.S_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'THROWING_ROCK',        skillName: 'ROCK',           skillGroup: WType.RANGED, damage: [new Roll(1, 4)],    ap: 0, damageTypes: [DMG.CRUSHING], weight: 0.25, minSTR: 0, minDEX: 0, rune: Runes.DARKNESS, fireRate: FireRateEnum.S_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'THROWING_SPIKE',       skillName: 'THROWING_SPIKE', skillGroup: WType.RANGED, damage: [new Roll(1, 4)],    ap: 6, damageTypes: [DMG.IMPALING], weight: 0.25, minSTR: 9, minDEX: 9,                    fireRate: FireRateEnum.S_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'THROWING_STAR',        skillName: 'THROWING_STAR',  skillGroup: WType.RANGED, damage: [new Roll(1, 3)],    ap: 3, damageTypes: [DMG.IMPALING], weight: 0.25, minSTR: 7, minDEX: 9,                    fireRate: FireRateEnum.S_MR, rangue: 20, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'THROWING_RING',        skillName: 'THROWING_RING',  skillGroup: WType.RANGED, damage: [new Roll(1, 6)],    ap: 8, damageTypes: [DMG.SLASHING], weight: 0.33, minSTR: 7, minDEX: 11,                   fireRate: FireRateEnum.S_MR, rangue: 30, damageModType: DamageModTypeEnum.HALF }),
  WF.createWeapon({ name:'BOLA',                 skillName: 'BOLA',        skillGroup: WType.RANGED, damage: [new Roll(1, 3)], ap: 3, damageTypes: [DMG.CRUSHING], weight: 0.25, minSTR: 9, minDEX: 9,  fireRate: FireRateEnum.E_MR, rangue: 20 }),
  WF.createWeapon({ name:'COMNBAT_NET',          skillName: 'COMNBAT_NET', skillGroup: WType.RANGED, damage: [],               ap: 8, damageTypes: [],             weight: 1,    minSTR: 9, minDEX: 11, fireRate: FireRateEnum.E_MR, rangue:  5 }),
];

export const SHIELDS: Weapon[] = [
  WF.createWeapon({ name: 'APRON',                  skillName: 'APRON',        skillGroup: WType.MELEE, damage: [],                   ap: 2, mr: 3, damageTypes: [],             weight: 1, minSTR: 1, minDEX: 0 }),
  WF.createWeapon({ name: 'BRONCE_SHIELD_HAND',     skillName: 'HAND_SHIELD',  skillGroup: WType.MELEE, damage: [new Roll(1, 3)],     ap: 8, mr: 3, damageTypes: [DMG.CRUSHING], weight: 1, minSTR: 8, minDEX: 0 }),
  WF.createWeapon({ name: 'BLADED_SHIELD',          skillName: 'SMALL_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 3, 1)],  ap: 8, mr: 3, damageTypes: [DMG.SLASHING], weight: 2, minSTR: 8, minDEX: 0 }),
  WF.createWeapon({ name: 'BRONCE_SHIELD',          skillName: 'SMALL_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 4)],     ap: 12,mr: 3, damageTypes: [DMG.CRUSHING], weight: 2, minSTR: 8, minDEX: 0 }),
  WF.createWeapon({ name: 'SMALL_SPICKED_SHIELD',   skillName: 'SMALL_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 3, 1)],  ap: 10,mr: 3, damageTypes: [DMG.IMPALING], weight: 2, minSTR: 9, minDEX: 0 }),
  WF.createWeapon({ name: 'HIDE_SMALL_SHIELD',      skillName: 'SMALL_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 3)],     ap: 8, mr: 3, damageTypes: [DMG.CRUSHING], weight: 1, minSTR: 5, minDEX: 0 }),
  WF.createWeapon({ name: 'WOOD_SMALL_SHIELD',      skillName: 'SMALL_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 3)],     ap: 8, mr: 3, damageTypes: [DMG.CRUSHING], weight: 1, minSTR: 5, minDEX: 0 }),
  WF.createWeapon({ name: 'THURTLESHELL_SHIELD',    skillName: 'SMALL_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 3)],     ap: 10,mr: 3, damageTypes: [DMG.CRUSHING], weight: 2, minSTR: 7, minDEX: 0 }),
  WF.createWeapon({ name: 'HIDE_MEDIUM_SHIELD',     skillName: 'MEDIUM_SHIELD',skillGroup: WType.MELEE, damage: [new Roll(1, 4)],     ap: 12,mr: 3, damageTypes: [DMG.CRUSHING], weight: 2, minSTR: 9, minDEX: 0 }),
  WF.createWeapon({ name: 'WOOD_MEDIUM_SHIELD',     skillName: 'MEDIUM_SHIELD',skillGroup: WType.MELEE, damage: [new Roll(1, 4)],     ap: 12,mr: 3, damageTypes: [DMG.CRUSHING], weight: 2, minSTR: 9, minDEX: 0 }),
  WF.createWeapon({ name: 'WICKER_MEDIUM_SHIELD',   skillName: 'MEDIUM_SHIELD',skillGroup: WType.MELEE, damage: [new Roll(1, 4)],     ap: 12,mr: 3, damageTypes: [DMG.CRUSHING], weight: 2, minSTR: 9, minDEX: 0 }),
  WF.createWeapon({ name: 'INSECT_CAPARACE_SHIELD', skillName: 'MEDIUM_SHIELD',skillGroup: WType.MELEE, damage: [new Roll(1, 4)],     ap: 12,mr: 3, damageTypes: [DMG.CRUSHING], weight: 2, minSTR: 9, minDEX: 0 }),
  WF.createWeapon({ name: 'MEDIUM_SPICKED_SHIELD',  skillName: 'MEDIUM_SHIELD',skillGroup: WType.MELEE, damage: [new Roll(1, 4, 1)],  ap: 12,mr: 3, damageTypes: [DMG.IMPALING], weight: 2, minSTR: 9, minDEX: 0 }),
  WF.createWeapon({ name: 'HIDE_LARGE_SHIELD',      skillName: 'LARGE_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 6)],     ap: 16,mr: 3, damageTypes: [DMG.CRUSHING], weight: 3, minSTR: 12,minDEX: 0 }),
  WF.createWeapon({ name: 'WOOD_LARGE_SHIELD',      skillName: 'LARGE_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 6)],     ap: 16,mr: 3, damageTypes: [DMG.CRUSHING], weight: 3, minSTR: 12,minDEX: 0 }),
  WF.createWeapon({ name: 'WICKER_LARGE_SHIELD',    skillName: 'LARGE_SHIELD', skillGroup: WType.MELEE, damage: [new Roll(1, 6)],     ap: 16,mr: 3, damageTypes: [DMG.CRUSHING], weight: 3, minSTR: 12,minDEX: 0 }),
  WF.createWeapon({ name: 'WICKER_EXTRALAEGE_SHIELD',skillName: 'EXTRA_LARGE_SHIELD',skillGroup: WType.MELEE, damage: [new Roll(1, 6)], ap: 19,mr: 3, damageTypes: [DMG.CRUSHING], weight: 5, minSTR: 14,minDEX: 0 }),
];

const HEAD: LocationsEnum[] = [LocationsEnum.HEAD];
const ARMS: LocationsEnum[] = [LocationsEnum.RIGHT_ARM, LocationsEnum.LEFT_ARM];
const CHEST: LocationsEnum[] = [LocationsEnum.CHEST];
const TORSO: LocationsEnum[] = [LocationsEnum.CHEST, LocationsEnum.ABDOMEN];
const ABDOMEN: LocationsEnum[] = [LocationsEnum.ABDOMEN];
const LEGS: LocationsEnum[] = [LocationsEnum.RIGHT_LEG, LocationsEnum.LEFT_LEG];
const PANTS: LocationsEnum[] = [LocationsEnum.RIGHT_LEG, LocationsEnum.LEFT_LEG, LocationsEnum.ABDOMEN];

export const ARMORS: Armor[] = [
  new Armor(ArmorMat.LEATHER, ArmorTypes.HOOD,              HEAD, 1, 0.5, 3, 0),
  new Armor(ArmorMat.LEATHER, ArmorTypes.BROAD_BRIMMED_HAT, HEAD, 1, 0.5, 4, 0),
  new Armor(ArmorMat.LEATHER, ArmorTypes.CAP,               HEAD, 2, 0.5, 5, 0),
  new Armor(ArmorMat.PLATE, ArmorTypes.COMPOSITE_HELM,      HEAD, 3, 0.5, 10, 0),
  new Armor(ArmorMat.RHINO_HIDE, ArmorTypes.COMPOSITE_HELM, HEAD, 4, 1, 40, 0),
  new Armor(ArmorMat.PLATE, ArmorTypes.OPEN_HELM,           HEAD, 4, 1, 20, 0),
  new Armor(ArmorMat.PLATE, ArmorTypes.CLOSED_HELM,         HEAD, 5, 1, 30, 0),
  new Armor(ArmorMat.PLATE, ArmorTypes.FULL_HELM,           HEAD, 6, 2, 50, 0),

  new Armor(ArmorMat.LIGTH_SCALE, ArmorTypes.SLEEVES,       ARMS, 4, 2, 25, -15),
  new Armor(ArmorMat.HEAVY_SCALE, ArmorTypes.SLEEVES,       ARMS, 5, 3, 50, -15),
  new Armor(ArmorMat.LEATHER, ArmorTypes.VAMBRACES,         ARMS, 1, 0.5, 10, 0),
  new Armor(ArmorMat.CUIRBOILLI, ArmorTypes.VAMBRACES,      ARMS, 3, 1, 30, 0),
  new Armor(ArmorMat.RHINO_HIDE, ArmorTypes.VAMBRACES,      ARMS, 5, 1, 60, -5),
  new Armor(ArmorMat.BRONCE_PLATE, ArmorTypes.VAMBRACES,    ARMS, 6, 2, 100, -10),

  new Armor(ArmorMat.LEATHER, ArmorTypes.CUIRASS,          CHEST, 1, 1, 10, 0),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.CUIRASS,    CHEST, 2, 1, 20, 0),
  new Armor(ArmorMat.RING_MAIL, ArmorTypes.CUIRASS,        CHEST, 4, 1, 50, -5),
  new Armor(ArmorMat.TURTLESHELL, ArmorTypes.CUIRASS,      CHEST, 4, 1, 15, 0),
  new Armor(ArmorMat.INSECT_CAPARACE, ArmorTypes.CUIRASS,  CHEST, 4, 1, 100, 0),
  new Armor(ArmorMat.LIGTH_SCALE, ArmorTypes.CUIRASS,      CHEST, 4, 1, 25, -10),
  new Armor(ArmorMat.RHINO_HIDE, ArmorTypes.CUIRASS,       CHEST, 5, 2, 120, -5),
  new Armor(ArmorMat.HEAVY_SCALE, ArmorTypes.CUIRASS,      CHEST, 5, 3, 40, -25),
  new Armor(ArmorMat.DISK_PLATE, ArmorTypes.CUIRASS,       CHEST, 5, 2, 100, -15),
  new Armor(ArmorMat.BRONCE_PLATE, ArmorTypes.CUIRASS,     CHEST, 6, 3, 175, -15),

  new Armor(ArmorMat.QUILTED, ArmorTypes.LINOTORAX,        TORSO, 2, 1, 20, 0),
  new Armor(ArmorMat.LINEN, ArmorTypes.LINOTORAX,          TORSO, 3, 1, 30, -5),
  new Armor(ArmorMat.LEATHER, ArmorTypes.HAUBERK,          TORSO, 1, 0.5, 20, 0),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.HAUBERK,    TORSO, 2, 1, 40, 0),
  new Armor(ArmorMat.RING_MAIL, ArmorTypes.HAUBERK,        TORSO, 4, 2, 80, -15),
  new Armor(ArmorMat.LIGTH_SCALE, ArmorTypes.HAUBERK,      TORSO, 4, 2, 40, -20),
  new Armor(ArmorMat.RHINO_HIDE, ArmorTypes.HAUBERK,       TORSO, 5, 3, 150, -5),
  new Armor(ArmorMat.HEAVY_SCALE, ArmorTypes.HAUBERK,      TORSO, 5, 3, 65, -25),
  new Armor(ArmorMat.PLATE, ArmorTypes.SEGMENTED_BRONCE,   TORSO, 6, 5, 300, -50),

  new Armor(ArmorMat.LEATHER, ArmorTypes.SKIRTS,           ABDOMEN, 1, 0.5, 10, 0),
  new Armor(ArmorMat.LINEN, ArmorTypes.SKIRTS,             ABDOMEN, 3, 1, 20, 0),
  new Armor(ArmorMat.STUDDED_LEATHER, ArmorTypes.SKIRTS,   ABDOMEN, 3, 1, 20, -5),
  new Armor(ArmorMat.LIGTH_SCALE, ArmorTypes.SKIRTS,       ABDOMEN, 4, 2, 30, -15),
  new Armor(ArmorMat.RHINO_HIDE, ArmorTypes.SKIRTS,        ABDOMEN, 4, 3, 80, -10),
  new Armor(ArmorMat.HEAVY_SCALE, ArmorTypes.SKIRTS,       ABDOMEN, 5, 3, 60, -30),

  new Armor(ArmorMat.LEATHER, ArmorTypes.PANTS,           PANTS, 1, 0.5, 10, 0),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.PANTS,     PANTS, 2, 1, 20, 0),
  new Armor(ArmorMat.LEATHER, ArmorTypes.TREWS,           PANTS, 1, 0.5, 10, 0),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.TREWS,     PANTS, 2, 1, 20, 0),

  new Armor(ArmorMat.LEATHER, ArmorTypes.GREAVES,         LEGS, 1, 0.5, 15, 0),
  new Armor(ArmorMat.CUIRBOILLI, ArmorTypes.GREAVES,      LEGS, 3, 1, 40, 0),
  new Armor(ArmorMat.RHINO_HIDE, ArmorTypes.GREAVES,      LEGS, 5, 2, 100, -5),
  new Armor(ArmorMat.BRONCE_PLATE, ArmorTypes.GREAVES,    LEGS, 6, 2, 120, -15),

];

export const NON_HUMAN_ARMMORS: Armor[] = [
  new Armor(ArmorMat.ELF_BARK, ArmorTypes.HOOD,            HEAD, 2, 0.5, 12, +5, ['ELF']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.HOOD,             HEAD, 1, 0.25, 2, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.BROAD_BRIMMED_HAT,HEAD, 1, 0.25, 3, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.CAP,              HEAD, 2, 0.5,   3, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.PLATE, ArmorTypes.COMPOSITE_HELM,     HEAD, 3, 0.25, 10, 0, ['DUCK']),
  new Armor(ArmorMat.LEAD_PLATE, ArmorTypes.OPEN_HELM,     HEAD, 4, 1, 80, 0, ['TROLL']),
  new Armor(ArmorMat.LEAD_PLATE, ArmorTypes.CLOSED_HELM,   HEAD, 5, 2, 70, 0, ['TROLL']),

  new Armor(ArmorMat.ELF_BARK, ArmorTypes.SLEEVES,         ARMS, 2, 0.5, 45, +5, ['ELF']),
  new Armor(ArmorMat.LIGTH_SCALE, ArmorTypes.SLEEVES,      ARMS, 4, 0.5, 25, 0, ['DUCK']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.VAMBRACES,        ARMS, 1, 0.125, 10, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.CUIRBOILLI, ArmorTypes.VAMBRACES,     ARMS, 3, 0.5, 30, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.LEAD_PLATE, ArmorTypes.VAMBRACES,     ARMS, 6, 2, 80, 0, ['TROLL']),

  new Armor(ArmorMat.ELF_BARK, ArmorTypes.CUIRASS,         CHEST, 2, 2, 45, +5, ['ELF']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.CUIRASS,          CHEST, 1, 0.2, 5, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.CUIRASS,    CHEST, 2, 0.5, 15, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.TURTLESHELL, ArmorTypes.CUIRASS,      CHEST, 4, 0.5, 10, 0, ['DUCK']),
  new Armor(ArmorMat.INSECT_CAPARACE, ArmorTypes.CUIRASS,  CHEST, 4, 0.5, 100, 0, ['TROLL']),
  new Armor(ArmorMat.LIGTH_SCALE, ArmorTypes.CUIRASS,      CHEST, 4, 1, 25, -10, ['DUCK']),
  new Armor(ArmorMat.LEAD_PLATE, ArmorTypes.CUIRASS,       CHEST, 6, 4, 120, 0, ['TROLL']),

  new Armor(ArmorMat.QUILTED, ArmorTypes.LINOTORAX,       TORSO, 2, 0.5, 15, 0, ['TROLLKIN']),
  new Armor(ArmorMat.LINEN, ArmorTypes.LINOTORAX,         TORSO, 3, 0.5, 25, -5, ['TROLLKIN']),
  new Armor(ArmorMat.ELF_BARK, ArmorTypes.HAUBERK,        TORSO, 2, 1, 80, +5, ['ELF']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.HAUBERK,         TORSO, 1, 0.5, 15, 0, ['DUCK','TROLLKIN']),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.HAUBERK,   TORSO, 2, 0.5, 20, 0, ['TROLLKIN']),

  new Armor(ArmorMat.LEATHER, ArmorTypes.PANTS,           PANTS, 1, 0.5, 3, 0, ['TROLLKIN']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.TREWS,           PANTS, 1, 0.5, 3, 0, ['TROLLKIN']),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.PANTS,     PANTS, 2, 0.5, 10, 0, ['TROLLKIN']),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.TREWS,     PANTS, 2, 0.5, 10, 0, ['TROLLKIN']),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.PANTS,     PANTS, 2, 1, 20, 0, ['TROLL']),
  new Armor(ArmorMat.HEAVY_LEATHER, ArmorTypes.TREWS,     PANTS, 2, 1, 20, 0, ['TROLL']),

  new Armor(ArmorMat.ELF_BARK, ArmorTypes.GREAVES,        LEGS, 2, 1, 80, +5, ['ELF']),
  new Armor(ArmorMat.LEATHER, ArmorTypes.GREAVES,         LEGS, 1, 0.25, 10, 0, ['TROLLKIN']),
  new Armor(ArmorMat.CUIRBOILLI, ArmorTypes.GREAVES,      LEGS, 1, 0.5, 20, 0, ['TROLLKIN']),
  new Armor(ArmorMat.LEAD_PLATE, ArmorTypes.GREAVES,      LEGS, 6, 2, 100, 0, ['TROLL']),
];
