export enum StatModifierType {
  NEGATIVE_PRIMARY = 'NEGATIVE_PRIMARY',
  NEGATIVE_SECONDARY = 'NEGATIVE_SECONDARY',
  POSITIVE_PRIMARY = 'POSITIVE_PRIMARY',
  POSITIVE_SECONDARY = 'POSITIVE_SECONDARY',
}
